type Lang="en"|"ru";
const copy={
 en:{nav:["Stays","Journal"],book:"Book your stay ↗",eyebrow:"68° NORTH · NORWAY",title:<>Sleep under<br/>another sky.</>,lead:"Three secluded cabins. Endless Arctic quiet. A front-row seat to the northern lights.",tonight:"Tonight",forecast:"Clear sky · Aurora likely",explore:"Explore ↓",kicker:"A slower kind of travel",introTitle:<>Nothing between<br/>you and the wild.</>,intro:"Set deep in the Lyngen Alps, Aurora Stays is an off-grid retreat shaped by silence, snow and Scandinavian restraint.",facts:[["03","private cabins"],["24h","hosted care"],["0","light pollution"]],view:"Choose your view",season:"Winter season · Oct—Mar",cabins:[["Glass House","2 guests · private sauna"],["Pine Shelter","4 guests · forest deck"],["Sky Loft","2 guests · panorama roof"]],from:"from",ctaSmall:"Only the sky is busy here.",cta:<>Meet winter<br/>at its quietest.</>,availability:"Check availability ↗",location:"Lyngen Alps, Norway"},
 ru:{nav:["Домики","Журнал"],book:"Забронировать ↗",eyebrow:"68° СЕВЕРНОЙ ШИРОТЫ · НОРВЕГИЯ",title:<>Спите под<br/>другим небом.</>,lead:"Три уединённых дома. Бескрайняя арктическая тишина. Северное сияние в первом ряду.",tonight:"Сегодня",forecast:"Ясно · Сияние вероятно",explore:"Исследовать ↓",kicker:"Путешествие в медленном ритме",introTitle:<>Между вами<br/>и дикой природой — ничего.</>,intro:"Aurora Stays спрятан в Люнгенских Альпах: автономный северный ретрит, созданный из тишины, снега и скандинавской сдержанности.",facts:[["03","частных дома"],["24/7","забота хозяев"],["0","светового шума"]],view:"Выберите свой вид",season:"Зимний сезон · октябрь—март",cabins:[["Стеклянный дом","2 гостя · личная сауна"],["Сосновый приют","4 гостя · лесная терраса"],["Небесный лофт","2 гостя · панорамная крыша"]],from:"от",ctaSmall:"Здесь занято только небо.",cta:<>Встретьте зиму<br/>в её самой тихой точке.</>,availability:"Проверить даты ↗",location:"Люнгенские Альпы, Норвегия"}
} as const;
const prices=["€390","€470","€520"];
export function SiteHome({lang}:{lang:Lang}){const c=copy[lang],prefix=lang==="ru"?"/ru":"/en";return <main data-lang={lang}><div className="lang-float"><a className={lang==="en"?"active":""} href="/">EN</a><a className={lang==="ru"?"active":""} href="/ru">RU</a></div>
 <section className="hero" id="top"><nav><a className="brand" href="#top"><span>▲</span> AURORA</a><div className="navlinks"><a href={`${prefix}/stays`}>{c.nav[0]}</a><a href={`${prefix}/journal`}>{c.nav[1]}</a></div><a className="book" href="#book">{c.book}</a></nav><div className="eyebrow">{c.eyebrow}</div><div className="hero-copy"><h1>{c.title}</h1><p>{c.lead}</p></div><div className="aurora" aria-hidden="true"><i/><i/><i/></div><div className="weather"><span>{c.tonight}</span><b>−8°</b><small>{c.forecast}</small></div><a className="scroll" href="#stays">{c.explore}</a></section>
 <section className="intro" id="story"><p className="kicker">{c.kicker}</p><h2>{c.introTitle}</h2><div className="intro-grid"><p>{c.intro}</p><div className="facts">{c.facts.map(([n,l])=><span key={l}><b>{n}</b>{l}</span>)}</div></div></section>
 <section className="stays" id="stays"><div className="section-head"><p>{c.view}</p><span>{c.season}</span></div>{c.cabins.map(([name,meta],i)=><a className="stay" href="#book" key={name}><span>0{i+1}</span><h3>{name}</h3><p>{meta}</p><strong>{c.from} {prices[i]}</strong><i>↗</i></a>)}</section>
 <section className="cta" id="book"><p>{c.ctaSmall}</p><h2>{c.cta}</h2><a href="mailto:stay@aurora.example">{c.availability}</a></section><footer><a className="brand" href="#top"><span>▲</span> AURORA</a><p>{c.location}</p><p>© 2026 Aurora Stays</p></footer></main>}
